# Generated by Django 4.0.3 on 2022-08-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_like_board_unlike_alter_board_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('manager', 'manager on site'),)},
        ),
    ]
