# Generated by Django 4.0.3 on 2022-03-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_board_boards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
    ]
