# Generated by Django 4.0.3 on 2022-05-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
    ]
