# Generated by Django 4.0.3 on 2022-05-08 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_comment_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 13, 19, 9, 736190, tzinfo=utc)),
        ),
    ]
