# Generated by Django 4.0.3 on 2022-05-08 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_comment_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 13, 30, 22, 560387, tzinfo=utc)),
        ),
    ]
