# Generated by Django 4.0.3 on 2022-05-08 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_board_comment_alter_comment_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 14, 7, 10, 154153, tzinfo=utc)),
        ),
    ]
