# Generated by Django 4.0.3 on 2022-05-08 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_board_comment_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='board',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 14, 10, 23, 467882, tzinfo=utc)),
        ),
    ]
