# Generated by Django 4.0.3 on 2022-06-05 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_rename_comment_comment_board_alter_comment_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='update_date',
        ),
        migrations.AddField(
            model_name='board',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 8, 25, 21, 770727, tzinfo=utc)),
        ),
    ]
