# Generated by Django 4.0.4 on 2022-05-14 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_rename_comment_comment_board_alter_comment_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 11, 31, 39, 564308, tzinfo=utc)),
        ),
    ]
