# Generated by Django 4.0.3 on 2022-06-05 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_comment_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 8, 51, 15, 527310, tzinfo=utc)),
        ),
    ]
